---
title: "Logistic Regression"
author: "Felix Eßer"
date: "11/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
discrete dependent variables 
Predicting of Y occuring given known values of predictors


Odds: Probability of an event occurring divided through the probability of the event not occurring


<table width="750">
  <thead>
    <tr>
      <th></th>
      <th colspan="2">Range</th>
      <th colspan="3">Occurrence of Event</th>
    </tr>
    <tr style="text-align: center">
      <th></th>
      <th>Minimum</th> <th>Maximum</th>
      <th>Maximum Uncertainty</th> <th>Less Probable</th> <th>More Probable</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Dependent Probability</td>
      <td style="text-align: center">$0$</td>
      <td style="text-align: center">$1$</td>
      <td style="text-align: center">$0.5$</td>
      <td style="text-align: center">$\lt 0.5$</td>
      <td style="text-align: center">$\gt 0.5$</td>
    </tr>
    <tr>
      <td>Odds</td>
      <td style="text-align: center">$0$</td>
      <td style="text-align: center">$1$</td>
      <td style="text-align: center">$1$</td>
      <td style="text-align: center">$\lt 1$</td>
      <td style="text-align: center">$\gt 1$</td>
    </tr>
    <tr>
      <td>Logit</td>
      <td style="text-align: center">$0$</td>
      <td style="text-align: center">$1$</td>
      <td style="text-align: center">$0$</td>
      <td style="text-align: center">$\lt 0$</td>
      <td style="text-align: center">$\gt 0$</td>
    </tr>
  </tbody>
</table>



 


# Binary Logistic Regression 
binary/dichotomous dependent variable 


## Assumptions of Logistic Regression

1. Binary dependent variable fullfilling the MECE-rule
    - MECE = mutually exclusive and collectively exhaustive; meaning one case must be classified in one and only one of the two dependent categories of the binary dependent variable
2. Independent observations
3. Conditional binomial distribution
    - implies that the conditional variance is 
4. Absence of multicolinearity
5. Linear realtionship between predictors and logit
    - test the interaction effect between the predictor and the natural log of the predictor



# Multinomial Logistic Regression
multinomial/polychotomous dependent variable



# Theory and Mathematics of Logisitic Regression