---
title: "Correlation"
author: "Felix Eßer"
date: "10/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction and Overview

# Two Nominal Variables

## Two Dichotomous Variables

### The $\varphi$ coefficient - Product-Moment-Correlation of dichotomous variables

value range: [-1, +1]
boundary value can only be obtained if relationship is perfect **and** both variables have the same distribution.

The more both distributions differ, the smaller the possible absolute value of $\varphi$.

There are corrections but it is easier to use other correlation measures for dichotomous variables.

### Yules Q

### Odds-Ratio

### Tetrachoric Correlation

Application of the polychoric correlation on dichotomous variables.


## Two Polytomous Variables

### Contingency Coefficient

Based on $\chi^2$ value. 
inferior to Cramer's $V$ becauseit can never reach it's upper boundary!

### Cramer's $V$

Based on the $\chi^2$ value
is identical to $\varphi$ in the case of dichotomous variables. 
value range: [0, 1]



## A Dichotomous and a Polytomous Variable

### Cramer's $V$


# Two Ordinal Variables

Kendall's $\tau$
-> used for singular ordinal variables without tied ranks

$e$ coefficient
--> used for singular ordinal variables with tied ranks


$\gamma$ coefficient
-> used for ordinal variables with ordered categories


polychoric correlation
-> used for ordinal variables with ordered categories
-> assumes that metric normally distributed variables underlie both ordinal variables with 


Somer's $d$
-> used for a singular ordinal variable (can have ties) and a ordinal variable with ordered categories

# Two Metric Variables

## Pearson's Product-Moment-Correlation

value range: $[-1, +1]$



# A Nominal and a Ordinal Variable

# A Nominal and a Metric Variable

dichotomous nominal variable:
point-biserial correlation
biserial correlation

polytomous nominal variable:
eta = square root of eta squared (from ANOVA)
-> eta for dichotomous nominal variable corresponds with point-biserial correlation


# A Ordinal and a Metric Variable

ordinal variable with ordered categories
polyserial correlation
- assumes that a metric variable underlies the ordinal variable


singular ordinal variable








# Appendix: Theory and Mathematics of the Correlation Coefficients




# Two Metric Variables

$$CP_{XY} = \sum^n_{i = 1} (x_i - \bar{x}) \cdot (y_i - \bar{y})$$



