---
title: "Correlation Matrices"
author: "Felix Eßer"
date: "4/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
Often it is of interest to get the correlations of several variables among each other and not only one correlation of one pair of variables. These correlations are often arranged in a correlation matrix. 

A correlation matrix is a $p \times p$ matrix, where $p$ denotes the number of variables. Within a correlation matrix
- correlations on the principal diagonal represent the correlation of the variable with itself which equals the variances of the variable
- correlations on the off-diagonals are correlations between variables

Usually, correlation matrices are presented in tables accompanying other descriptive statistics like the means and standard deviations of the $p$ variables. In addition, it is possible to visualize correlation matrices in several ways.

As several correlations are calculated and often tested for significance, it is often important to adjust the $p$-values of the significance tests because multiple tests are conducted. 

In the following, only the pearson correlation is used, but it is possible for all other correlations too (link to Correlation file). The pearson correlation is the most used correlation coefficient and is consequently supported the most. Therefore, convenient packages are shown as well as calculation *by hand* in a loop (link to loops) in order to obtain results for less supported correlation measures.

# Packages and data
# Correlation matrix
## Correlation matrix using the built-in `{stats}` package
## Correlation matrix using the `{correlation}` package
## Manual creation of a correlation matrix
# $p$-value adjustment
## $p$-value adjustment with the `{correlation}` package
## Manual $p$-value adjustment
# Tables
# Visualization
## Symbolic number encoding
## Correlogram
## Network graph for Correlations
